In [6]:
import pandas as pd
import datetime as dt

In [7]:
csv = 'Merged_Datasets/France_Monthly.csv'
df = pd.read_csv(csv)

df.head()

,Year,Month,canada_unemployment_rates,unemployment_rates,canada_inflation_rate,inflation_rate,canada_total_cases,canada_total_tests,canada_people_fully_vaccinated,canada_total_deaths,canada_reproduction_rate,total_cases,total_tests,people_fully_vaccinated,total_deaths,reproduction_rate
0,2019,1,5.9,8.7,1.4,1.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019,2,5.9,8.7,1.5,1.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019,3,5.8,8.7,1.9,1.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019,4,5.8,8.5,2.0,1.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019,5,5.4,8.6,2.4,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df['Date'] = pd.to_datetime(df[['Year', 'Month']].assign(DAY=1))
df['Date'] = df['Date'].apply(lambda x: x.strftime('%Y-%m'))
df.head()

,Year,Month,canada_unemployment_rates,unemployment_rates,canada_inflation_rate,inflation_rate,canada_total_cases,canada_total_tests,canada_people_fully_vaccinated,canada_total_deaths,canada_reproduction_rate,total_cases,total_tests,people_fully_vaccinated,total_deaths,reproduction_rate,Date
0,2019,1,5.9,8.7,1.4,1.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01
1,2019,2,5.9,8.7,1.5,1.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-02
2,2019,3,5.8,8.7,1.9,1.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-03
3,2019,4,5.8,8.5,2.0,1.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-04
4,2019,5,5.4,8.6,2.4,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05